# These hard-macro inputs are tied low by the top-level RTL. OpenSTA still
# reports constant macro inputs as endpoints after case analysis, so each
# known-static pin also receives a narrowly scoped false path.

# resetn asynchronously asserts only the two-flop reset synchronizer. uart_rx
# is asynchronous by protocol and terminates at the first synchronizer flop.
# All downstream reset and UART paths remain timed by clk.
set_false_path -from [get_ports resetn]
set_false_path -from [get_ports uart_rx]

# core_resetn is generated by the two-flop synchronizer and only drives
# asynchronous reset pins. Its deassertion is synchronous; data timing must not
# apply setup/hold checks to RESET_B/resetn pins. Electrical transition,
# capacitance and fanout checks remain active on this network.
set_false_path -to [get_pins -hierarchical */RESET_B]
set_false_path -to [get_pins -hierarchical */resetn]

proc constrain_static_low {instance pin_name} {
    set hierarchical_pin [format {%s/%s} $instance $pin_name]
    set pin [get_pins $hierarchical_pin]
    set_case_analysis 0 $pin
    set_false_path -to $pin
    set_disable_timing -from clk -to $pin_name [get_cells $instance]
    return
}

constrain_static_low u_axi coef_switch_busy
constrain_static_low u_axi coef_switch_pending
constrain_static_low u_peripherals spi_miso

for {set bit 1} {$bit < 32} {incr bit} {
    set pin_name [format {irq[%d]} $bit]
    constrain_static_low u_pico $pin_name
}
