// OpenLane child macro wrapper for AXI-Lite address decode and DPD registers.
module axi_ctrl_wrapper #(
    parameter COEF_WIDTH = 18,
    parameter COEF_ADDR_WIDTH = 7,
    parameter CAPTURE_ADDR_WIDTH = 10
)(
    input  wire clk,
    input  wire resetn,

    input  wire [31:0] m_awaddr,
    input  wire        m_awvalid,
    output wire        m_awready,
    input  wire [31:0] m_wdata,
    input  wire [3:0]  m_wstrb,
    input  wire        m_wvalid,
    output wire        m_wready,
    output wire [1:0]  m_bresp,
    output wire        m_bvalid,
    input  wire        m_bready,
    input  wire [31:0] m_araddr,
    input  wire        m_arvalid,
    output wire        m_arready,
    output wire [31:0] m_rdata,
    output wire [1:0]  m_rresp,
    output wire        m_rvalid,
    input  wire        m_rready,

    output wire [31:0] flash_araddr,
    output wire        flash_arvalid,
    input  wire        flash_arready,
    input  wire [31:0] flash_rdata,
    input  wire [1:0]  flash_rresp,
    input  wire        flash_rvalid,
    output wire        flash_rready,

    output wire [31:0] ram_awaddr,
    output wire        ram_awvalid,
    input  wire        ram_awready,
    output wire [31:0] ram_wdata,
    output wire [3:0]  ram_wstrb,
    output wire        ram_wvalid,
    input  wire        ram_wready,
    input  wire [1:0]  ram_bresp,
    input  wire        ram_bvalid,
    output wire        ram_bready,
    output wire [31:0] ram_araddr,
    output wire        ram_arvalid,
    input  wire        ram_arready,
    input  wire [31:0] ram_rdata,
    input  wire [1:0]  ram_rresp,
    input  wire        ram_rvalid,
    output wire        ram_rready,

    output wire [11:0] uart_awaddr,
    output wire        uart_awvalid,
    input  wire        uart_awready,
    output wire [31:0] uart_wdata,
    output wire [3:0]  uart_wstrb,
    output wire        uart_wvalid,
    input  wire        uart_wready,
    input  wire [1:0]  uart_bresp,
    input  wire        uart_bvalid,
    output wire        uart_bready,
    output wire [11:0] uart_araddr,
    output wire        uart_arvalid,
    input  wire        uart_arready,
    input  wire [31:0] uart_rdata,
    input  wire [1:0]  uart_rresp,
    input  wire        uart_rvalid,
    output wire        uart_rready,

    output wire [11:0] spi_awaddr,
    output wire        spi_awvalid,
    input  wire        spi_awready,
    output wire [31:0] spi_wdata,
    output wire [3:0]  spi_wstrb,
    output wire        spi_wvalid,
    input  wire        spi_wready,
    input  wire [1:0]  spi_bresp,
    input  wire        spi_bvalid,
    output wire        spi_bready,
    output wire [11:0] spi_araddr,
    output wire        spi_arvalid,
    input  wire        spi_arready,
    input  wire [31:0] spi_rdata,
    input  wire [1:0]  spi_rresp,
    input  wire        spi_rvalid,
    output wire        spi_rready,

    output wire        enable,
    output wire        force_bypass,
    output wire        capture_start_pulse,
    output wire        coef_switch_req_pulse,
    output wire        irq_clear_pulse,
    output wire        train_start_pulse,
    output wire [31:0] threshold_error,
    output wire [31:0] threshold_clip,
    output wire [31:0] threshold_drift,
    output wire [CAPTURE_ADDR_WIDTH-1:0] capture_len,
    output wire [CAPTURE_ADDR_WIDTH-1:0] train_sample_count,
    output wire [7:0]  feedback_delay,
    output wire        coef_we_a_pulse,
    output wire        coef_we_b_pulse,
    output wire [COEF_ADDR_WIDTH-1:0] coef_addr,
    output wire [COEF_WIDTH-1:0] coef_wdata,
    input  wire [COEF_WIDTH-1:0] coef_rdata_a,
    input  wire [COEF_WIDTH-1:0] coef_rdata_b,

    input  wire        dpd_active,
    input  wire        capture_busy,
    input  wire        capture_done,
    input  wire        capture_lock,
    input  wire        capture_ready,
    input  wire        train_busy,
    input  wire        train_done,
    input  wire        train_error,
    input  wire        coef_ready,
    input  wire        coef_switch_busy,
    input  wire        coef_switch_pending,
    input  wire        active_bank,
    input  wire        irq,
    input  wire [31:0] irq_status,
    input  wire [31:0] metric_power,
    input  wire [31:0] metric_error,
    input  wire [31:0] metric_clipping,
    input  wire [31:0] metric_drift,
    input  wire [31:0] mac_error_acc,
    output wire [31:0] irq_mask,
    output wire [31:0] irq_w1c
);
    wire [31:0] flash_awaddr_unused;
    wire        flash_awvalid_unused;
    wire [31:0] flash_wdata_unused;
    wire [3:0]  flash_wstrb_unused;
    wire        flash_wvalid_unused;
    wire        flash_bready_unused;

    wire [11:0] dpd_awaddr;
    wire        dpd_awvalid;
    wire        dpd_awready;
    wire [31:0] dpd_wdata;
    wire [3:0]  dpd_wstrb;
    wire        dpd_wvalid;
    wire        dpd_wready;
    wire [1:0]  dpd_bresp;
    wire        dpd_bvalid;
    wire        dpd_bready;
    wire [11:0] dpd_araddr;
    wire        dpd_arvalid;
    wire        dpd_arready;
    wire [31:0] dpd_rdata;
    wire [1:0]  dpd_rresp;
    wire        dpd_rvalid;
    wire        dpd_rready;

    axi_interconnect u_axi_interconnect (
        .clk(clk),
        .resetn(resetn),
        .m_awaddr(m_awaddr),
        .m_awvalid(m_awvalid),
        .m_awready(m_awready),
        .m_wdata(m_wdata),
        .m_wstrb(m_wstrb),
        .m_wvalid(m_wvalid),
        .m_wready(m_wready),
        .m_bresp(m_bresp),
        .m_bvalid(m_bvalid),
        .m_bready(m_bready),
        .m_araddr(m_araddr),
        .m_arvalid(m_arvalid),
        .m_arready(m_arready),
        .m_rdata(m_rdata),
        .m_rresp(m_rresp),
        .m_rvalid(m_rvalid),
        .m_rready(m_rready),
        .flash_awaddr(flash_awaddr_unused),
        .flash_awvalid(flash_awvalid_unused),
        .flash_awready(1'b1),
        .flash_wdata(flash_wdata_unused),
        .flash_wstrb(flash_wstrb_unused),
        .flash_wvalid(flash_wvalid_unused),
        .flash_wready(1'b1),
        .flash_bresp(2'b00),
        .flash_bvalid(1'b0),
        .flash_bready(flash_bready_unused),
        .flash_araddr(flash_araddr),
        .flash_arvalid(flash_arvalid),
        .flash_arready(flash_arready),
        .flash_rdata(flash_rdata),
        .flash_rresp(flash_rresp),
        .flash_rvalid(flash_rvalid),
        .flash_rready(flash_rready),
        .ram_awaddr(ram_awaddr),
        .ram_awvalid(ram_awvalid),
        .ram_awready(ram_awready),
        .ram_wdata(ram_wdata),
        .ram_wstrb(ram_wstrb),
        .ram_wvalid(ram_wvalid),
        .ram_wready(ram_wready),
        .ram_bresp(ram_bresp),
        .ram_bvalid(ram_bvalid),
        .ram_bready(ram_bready),
        .ram_araddr(ram_araddr),
        .ram_arvalid(ram_arvalid),
        .ram_arready(ram_arready),
        .ram_rdata(ram_rdata),
        .ram_rresp(ram_rresp),
        .ram_rvalid(ram_rvalid),
        .ram_rready(ram_rready),
        .uart_awaddr(uart_awaddr),
        .uart_awvalid(uart_awvalid),
        .uart_awready(uart_awready),
        .uart_wdata(uart_wdata),
        .uart_wstrb(uart_wstrb),
        .uart_wvalid(uart_wvalid),
        .uart_wready(uart_wready),
        .uart_bresp(uart_bresp),
        .uart_bvalid(uart_bvalid),
        .uart_bready(uart_bready),
        .uart_araddr(uart_araddr),
        .uart_arvalid(uart_arvalid),
        .uart_arready(uart_arready),
        .uart_rdata(uart_rdata),
        .uart_rresp(uart_rresp),
        .uart_rvalid(uart_rvalid),
        .uart_rready(uart_rready),
        .spi_awaddr(spi_awaddr),
        .spi_awvalid(spi_awvalid),
        .spi_awready(spi_awready),
        .spi_wdata(spi_wdata),
        .spi_wstrb(spi_wstrb),
        .spi_wvalid(spi_wvalid),
        .spi_wready(spi_wready),
        .spi_bresp(spi_bresp),
        .spi_bvalid(spi_bvalid),
        .spi_bready(spi_bready),
        .spi_araddr(spi_araddr),
        .spi_arvalid(spi_arvalid),
        .spi_arready(spi_arready),
        .spi_rdata(spi_rdata),
        .spi_rresp(spi_rresp),
        .spi_rvalid(spi_rvalid),
        .spi_rready(spi_rready),
        .dpd_awaddr(dpd_awaddr),
        .dpd_awvalid(dpd_awvalid),
        .dpd_awready(dpd_awready),
        .dpd_wdata(dpd_wdata),
        .dpd_wstrb(dpd_wstrb),
        .dpd_wvalid(dpd_wvalid),
        .dpd_wready(dpd_wready),
        .dpd_bresp(dpd_bresp),
        .dpd_bvalid(dpd_bvalid),
        .dpd_bready(dpd_bready),
        .dpd_araddr(dpd_araddr),
        .dpd_arvalid(dpd_arvalid),
        .dpd_arready(dpd_arready),
        .dpd_rdata(dpd_rdata),
        .dpd_rresp(dpd_rresp),
        .dpd_rvalid(dpd_rvalid),
        .dpd_rready(dpd_rready)
    );

    axi_lite_regs #(
        .COEF_WIDTH(COEF_WIDTH),
        .COEF_ADDR_WIDTH(COEF_ADDR_WIDTH),
        .CAPTURE_ADDR_WIDTH(CAPTURE_ADDR_WIDTH)
    ) u_axi_lite_regs (
        .clk(clk),
        .resetn(resetn),
        .s_axi_awaddr(dpd_awaddr),
        .s_axi_awvalid(dpd_awvalid),
        .s_axi_awready(dpd_awready),
        .s_axi_wdata(dpd_wdata),
        .s_axi_wstrb(dpd_wstrb),
        .s_axi_wvalid(dpd_wvalid),
        .s_axi_wready(dpd_wready),
        .s_axi_bresp(dpd_bresp),
        .s_axi_bvalid(dpd_bvalid),
        .s_axi_bready(dpd_bready),
        .s_axi_araddr(dpd_araddr),
        .s_axi_arvalid(dpd_arvalid),
        .s_axi_arready(dpd_arready),
        .s_axi_rdata(dpd_rdata),
        .s_axi_rresp(dpd_rresp),
        .s_axi_rvalid(dpd_rvalid),
        .s_axi_rready(dpd_rready),
        .enable(enable),
        .force_bypass(force_bypass),
        .capture_start_pulse(capture_start_pulse),
        .coef_switch_req_pulse(coef_switch_req_pulse),
        .irq_clear_pulse(irq_clear_pulse),
        .train_start_pulse(train_start_pulse),
        .threshold_error(threshold_error),
        .threshold_clip(threshold_clip),
        .threshold_drift(threshold_drift),
        .capture_len(capture_len),
        .train_sample_count(train_sample_count),
        .feedback_delay(feedback_delay),
        .coef_we_a_pulse(coef_we_a_pulse),
        .coef_we_b_pulse(coef_we_b_pulse),
        .coef_addr(coef_addr),
        .coef_wdata(coef_wdata),
        .coef_rdata_a(coef_rdata_a),
        .coef_rdata_b(coef_rdata_b),
        .dpd_active(dpd_active),
        .capture_busy(capture_busy),
        .capture_done(capture_done),
        .capture_lock(capture_lock),
        .capture_ready(capture_ready),
        .train_busy(train_busy),
        .train_done(train_done),
        .train_error(train_error),
        .coef_ready(coef_ready),
        .coef_switch_busy(coef_switch_busy),
        .coef_switch_pending(coef_switch_pending),
        .active_bank(active_bank),
        .irq(irq),
        .irq_status(irq_status),
        .metric_power(metric_power),
        .metric_error(metric_error),
        .metric_clipping(metric_clipping),
        .metric_drift(metric_drift),
        .mac_error_acc(mac_error_acc),
        .irq_mask(irq_mask),
        .irq_w1c(irq_w1c)
    );
endmodule
