#!/usr/bin/env python3
"""
Export OpenDPD GMP coefficients and golden vectors for rtl_v2 gmp_engine.

This version targets the full 39-term OpenDPD GMP checkpoint generated by:
  memory_length = 3
  degree        = 5

Coefficient bank format for rtl_v2:
  addr 2*k + 0 = real coefficient k, signed Q2.16 int18
  addr 2*k + 1 = imag coefficient k, signed Q2.16 int18

The current OpenDPD GMP checkpoint stores real-valued weights. The exported
imaginary coefficient entries are therefore zero, but the RTL datapath performs
full complex coefficient multiplication.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import struct
import zipfile
from pathlib import Path


DEFAULT_PT = Path(
    "/home/Ausilon/projeto_dpd/OpenDPD/save/"
    "ATSC3_A322_VV031_8K_256QAM_FS24M_AGGRESSIVE_ALIGNED/"
    "train_dpd/PA_S_0_M_GMP_H_23_F_64/"
    "DPD_S_0_M_GMP_H_15_F_64_P_39.pt"
)
DEFAULT_OUT = Path("/home/Ausilon/Desktop/dpd_v1/dpd_soc_min/datasets/opendpd_coeffs")

N_TERMS = 39
MEMORY_LENGTH = 3
DEGREE = 5
LOOKAHEAD = 2
DIRECTED_SAMPLES = 64

COEF_FRAC_BITS = 16
COEF_WIDTH = 18
COEF_MIN = -(1 << (COEF_WIDTH - 1))
COEF_MAX = (1 << (COEF_WIDTH - 1)) - 1

SAMPLE_WIDTH = 16
SAMPLE_MIN = -(1 << (SAMPLE_WIDTH - 1))
SAMPLE_MAX = (1 << (SAMPLE_WIDTH - 1)) - 1


def arshift(value: int, bits: int) -> int:
    return value >> bits


def sat16(value: int) -> int:
    return max(SAMPLE_MIN, min(SAMPLE_MAX, value))


def hex_word(value: int, width: int) -> str:
    digits = (width + 3) // 4
    return f"{value & ((1 << width) - 1):0{digits}X}"


def q216(value: float) -> int:
    quantized = int(round(value * (1 << COEF_FRAC_BITS)))
    return max(COEF_MIN, min(COEF_MAX, quantized))


def read_float_storage(pt_path: Path) -> list[float]:
    with zipfile.ZipFile(pt_path) as archive:
        data_names = [
            name for name in archive.namelist()
            if "/data/" in name and not name.endswith("/")
        ]
        if not data_names:
            raise RuntimeError(f"No tensor storage found in {pt_path}")
        raw = archive.read(sorted(data_names)[0])
    if len(raw) % 4:
        raise RuntimeError(f"Unexpected float32 storage byte length: {len(raw)}")
    return list(struct.unpack("<" + "f" * (len(raw) // 4), raw))


def term_description(idx: int) -> dict[str, int | str]:
    if idx < MEMORY_LENGTH:
        return {
            "term": f"linear x_window[{idx}]",
            "kind": "linear",
            "power": 0,
            "amp_window": -1,
            "x_window": idx,
        }
    rel = idx - MEMORY_LENGTH
    power = (rel // (MEMORY_LENGTH * MEMORY_LENGTH)) + 1
    rem = rel % (MEMORY_LENGTH * MEMORY_LENGTH)
    amp_window = rem // MEMORY_LENGTH
    x_window = rem % MEMORY_LENGTH
    return {
        "term": f"x_window[{x_window}] * abs_window[{amp_window}+{x_window}]^{power}",
        "kind": "nonlinear",
        "power": power,
        "amp_window": amp_window,
        "x_window": x_window,
    }


def iq_abs_q15(i_val: int, q_val: int) -> int:
    return min(0x7fff, int(math.sqrt(i_val * i_val + q_val * q_val)))


def amp_power_q15(amp: int, power: int) -> int:
    if power == 0:
        return 1 << 15
    value = amp
    for _ in range(1, power):
        value = arshift(value * amp, 15)
    return value


def basis_for_term(window: list[tuple[int, int]], amps: list[int], idx: int) -> tuple[int, int]:
    desc = term_description(idx)
    x_pos = int(desc["x_window"])
    xi, xq = window[x_pos]
    if desc["kind"] == "linear":
        return xi, xq
    amp_pos = int(desc["amp_window"]) + x_pos
    amp_pow = amp_power_q15(amps[amp_pos], int(desc["power"]))
    return arshift(xi * amp_pow, 15), arshift(xq * amp_pow, 15)


def complex_weighted_term(basis_i: int, basis_q: int, coef_i: int, coef_q: int) -> tuple[int, int]:
    real = arshift((basis_i * coef_i) - (basis_q * coef_q), COEF_FRAC_BITS)
    imag = arshift((basis_i * coef_q) + (basis_q * coef_i), COEF_FRAC_BITS)
    return real, imag


def gmp_opendpd_model(samples: list[tuple[int, int]], coef_i: list[int], coef_q: list[int]) -> list[tuple[int, int]]:
    padded = [(0, 0), (0, 0)] + samples + [(0, 0), (0, 0)]
    out: list[tuple[int, int]] = []
    for n in range(len(samples)):
        base = n
        five = padded[base:base + 5]
        window = five[0:3]
        amps = [iq_abs_q15(i_val, q_val) for i_val, q_val in five]
        acc_i = 0
        acc_q = 0
        for idx in range(N_TERMS):
            bi, bq = basis_for_term(window, amps, idx)
            ti, tq = complex_weighted_term(bi, bq, coef_i[idx], coef_q[idx])
            acc_i += ti
            acc_q += tq
        out.append((sat16(acc_i), sat16(acc_q)))
    return out


def write_iq_hex(path: Path, samples: list[tuple[int, int]]) -> None:
    with path.open("w", encoding="ascii") as handle:
        for i_val, q_val in samples:
            handle.write(f"{hex_word(i_val, 16)}{hex_word(q_val, 16)}\n")


def directed_samples(count: int) -> list[tuple[int, int]]:
    samples: list[tuple[int, int]] = []
    state = 0x1ACE_B00C
    for idx in range(count):
        state = (1664525 * state + 1013904223) & 0xFFFFFFFF
        rnd_i = ((state >> 16) & 0xFFFF) - 32768
        state = (1664525 * state + 1013904223) & 0xFFFFFFFF
        rnd_q = ((state >> 16) & 0xFFFF) - 32768

        envelope = 0.22 + 0.72 * ((idx % 17) / 16.0)
        tone_i = math.sin(2.0 * math.pi * idx / 7.0) + 0.45 * math.sin(2.0 * math.pi * idx / 19.0)
        tone_q = math.cos(2.0 * math.pi * idx / 11.0) - 0.35 * math.sin(2.0 * math.pi * idx / 5.0)
        dither_i = rnd_i / 32768.0 * 0.18
        dither_q = rnd_q / 32768.0 * 0.18

        i_val = int(round(22500.0 * envelope * (0.70 * tone_i + dither_i)))
        q_val = int(round(22500.0 * envelope * (0.70 * tone_q + dither_q)))
        samples.append((sat16(i_val), sat16(q_val)))
    return samples


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--pt", type=Path, default=DEFAULT_PT)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--prefix", default="coef_bank_openDPD")
    parser.add_argument("--directed-samples", type=int, default=DIRECTED_SAMPLES)
    args = parser.parse_args()

    weights = read_float_storage(args.pt)
    if len(weights) != N_TERMS:
        raise RuntimeError(f"Expected {N_TERMS} OpenDPD weights, got {len(weights)}")

    args.out_dir.mkdir(parents=True, exist_ok=True)

    coef_i = [q216(float(value)) for value in weights]
    coef_q = [0 for _ in weights]
    coef_bank: list[int] = []
    for real, imag in zip(coef_i, coef_q):
        coef_bank.append(real)
        coef_bank.append(imag)
    coef_bank.extend([0] * (128 - len(coef_bank)))

    coef_hex = args.out_dir / f"{args.prefix}.hex"
    with coef_hex.open("w", encoding="ascii") as handle:
        for value in coef_bank:
            handle.write(f"{hex_word(value, COEF_WIDTH)}\n")

    csv_path = args.out_dir / f"{args.prefix}_audit.csv"
    with csv_path.open("w", newline="", encoding="ascii") as handle:
        writer = csv.writer(handle)
        writer.writerow([
            "term_index", "term", "float_real", "float_imag",
            "real_q2_16_signed", "imag_q2_16_signed",
            "real_addr", "imag_addr", "real_hex18", "imag_hex18",
        ])
        for idx, value in enumerate(weights):
            desc = term_description(idx)
            writer.writerow([
                idx,
                desc["term"],
                f"{float(value):.10g}",
                "0",
                coef_i[idx],
                coef_q[idx],
                2 * idx,
                2 * idx + 1,
                hex_word(coef_i[idx], COEF_WIDTH),
                hex_word(coef_q[idx], COEF_WIDTH),
            ])

    samples = [
        (1200, -800),
        (-2400, 1600),
        (4096, -2048),
        (-8192, 4096),
        (12000, -9000),
        (-16000, 11000),
        (20000, -14000),
        (-23000, 17000),
    ]
    expected = gmp_opendpd_model(samples, coef_i, coef_q)

    # Two trailing zeros provide the OpenDPD leading/lookahead terms to RTL.
    samples_for_rtl = samples + [(0, 0)] * LOOKAHEAD
    samples_hex = args.out_dir / "gmp_opendpd_samples_iq_q15.hex"
    expected_hex = args.out_dir / "gmp_opendpd_expected_iq_q15.hex"
    write_iq_hex(samples_hex, samples_for_rtl)
    write_iq_hex(expected_hex, expected)

    full_samples = directed_samples(args.directed_samples)
    full_expected = gmp_opendpd_model(full_samples, coef_i, coef_q)
    full_samples_for_rtl = full_samples + [(0, 0)] * LOOKAHEAD
    full_samples_hex = args.out_dir / "gmp_opendpd_full_samples_iq_q15.hex"
    full_expected_hex = args.out_dir / "gmp_opendpd_full_expected_iq_q15.hex"
    write_iq_hex(full_samples_hex, full_samples_for_rtl)
    write_iq_hex(full_expected_hex, full_expected)

    meta = {
        "source_pt": str(args.pt),
        "source_weight_count": len(weights),
        "rtl_model": "OpenDPD GMP, memory_length=3, degree=5, 39 terms",
        "coefficient_format": "complex coefficient as real/imag signed Q2.16 int18 in adjacent addresses",
        "lookahead_samples": LOOKAHEAD,
        "note": "Checkpoint weights are real, so imaginary coefficient entries are zero.",
        "coef_hex": str(coef_hex),
        "audit_csv": str(csv_path),
        "samples_hex": str(samples_hex),
        "expected_hex": str(expected_hex),
        "full_directed_samples": args.directed_samples,
        "full_samples_hex": str(full_samples_hex),
        "full_expected_hex": str(full_expected_hex),
        "term_map": [term_description(idx) for idx in range(N_TERMS)],
    }
    meta_path = args.out_dir / f"{args.prefix}_metadata.json"
    meta_path.write_text(json.dumps(meta, indent=2), encoding="ascii")

    print(f"Wrote {coef_hex}")
    print(f"Wrote {csv_path}")
    print(f"Wrote {samples_hex}")
    print(f"Wrote {expected_hex}")
    print(f"Wrote {full_samples_hex}")
    print(f"Wrote {full_expected_hex}")
    print(f"Wrote {meta_path}")


if __name__ == "__main__":
    main()
