// OpenLane child macro wrapper for low-speed debug/control peripherals.
module peripherals_wrapper (
    input  wire clk,
    input  wire resetn,

    input  wire [11:0] uart_awaddr,
    input  wire        uart_awvalid,
    output wire        uart_awready,
    input  wire [31:0] uart_wdata,
    input  wire [3:0]  uart_wstrb,
    input  wire        uart_wvalid,
    output wire        uart_wready,
    output wire [1:0]  uart_bresp,
    output wire        uart_bvalid,
    input  wire        uart_bready,
    input  wire [11:0] uart_araddr,
    input  wire        uart_arvalid,
    output wire        uart_arready,
    output wire [31:0] uart_rdata,
    output wire [1:0]  uart_rresp,
    output wire        uart_rvalid,
    input  wire        uart_rready,
    output wire        uart_tx,
    input  wire        uart_rx,

    input  wire [11:0] spi_awaddr,
    input  wire        spi_awvalid,
    output wire        spi_awready,
    input  wire [31:0] spi_wdata,
    input  wire [3:0]  spi_wstrb,
    input  wire        spi_wvalid,
    output wire        spi_wready,
    output wire [1:0]  spi_bresp,
    output wire        spi_bvalid,
    input  wire        spi_bready,
    input  wire [11:0] spi_araddr,
    input  wire        spi_arvalid,
    output wire        spi_arready,
    output wire [31:0] spi_rdata,
    output wire [1:0]  spi_rresp,
    output wire        spi_rvalid,
    input  wire        spi_rready,
    output wire        spi_sck,
    output wire        spi_mosi,
    input  wire        spi_miso,
    output wire        spi_cs,

    input  wire        irq_clear_pulse,
    input  wire [31:0] irq_w1c,
    input  wire [31:0] irq_mask,
    input  wire        capture_done,
    input  wire        coef_switch_done,
    input  wire        metrics_valid,
    input  wire        metric_retrain_request,
    output wire [31:0] irq_status,
    output wire        irq,
    output wire        retrain_request
);
    axi_uart u_axi_uart (
        .clk(clk),
        .resetn(resetn),
        .s_axi_awaddr(uart_awaddr),
        .s_axi_awvalid(uart_awvalid),
        .s_axi_awready(uart_awready),
        .s_axi_wdata(uart_wdata),
        .s_axi_wstrb(uart_wstrb),
        .s_axi_wvalid(uart_wvalid),
        .s_axi_wready(uart_wready),
        .s_axi_bresp(uart_bresp),
        .s_axi_bvalid(uart_bvalid),
        .s_axi_bready(uart_bready),
        .s_axi_araddr(uart_araddr),
        .s_axi_arvalid(uart_arvalid),
        .s_axi_arready(uart_arready),
        .s_axi_rdata(uart_rdata),
        .s_axi_rresp(uart_rresp),
        .s_axi_rvalid(uart_rvalid),
        .s_axi_rready(uart_rready),
        .tx(uart_tx),
        .rx(uart_rx)
    );

    axi_spi u_axi_spi (
        .clk(clk),
        .resetn(resetn),
        .s_axi_awaddr(spi_awaddr),
        .s_axi_awvalid(spi_awvalid),
        .s_axi_awready(spi_awready),
        .s_axi_wdata(spi_wdata),
        .s_axi_wstrb(spi_wstrb),
        .s_axi_wvalid(spi_wvalid),
        .s_axi_wready(spi_wready),
        .s_axi_bresp(spi_bresp),
        .s_axi_bvalid(spi_bvalid),
        .s_axi_bready(spi_bready),
        .s_axi_araddr(spi_araddr),
        .s_axi_arvalid(spi_arvalid),
        .s_axi_arready(spi_arready),
        .s_axi_rdata(spi_rdata),
        .s_axi_rresp(spi_rresp),
        .s_axi_rvalid(spi_rvalid),
        .s_axi_rready(spi_rready),
        .spi_sck(spi_sck),
        .spi_mosi(spi_mosi),
        .spi_miso(spi_miso),
        .spi_cs(spi_cs)
    );

    irq_status_ctrl u_irq_status_ctrl (
        .clk(clk),
        .resetn(resetn),
        .clear_pulse(irq_clear_pulse),
        .w1c(irq_w1c),
        .mask(irq_mask),
        .capture_done(capture_done),
        .coef_switch_done(coef_switch_done),
        .metrics_valid(metrics_valid),
        .metric_retrain_request(metric_retrain_request),
        .status(irq_status),
        .irq(irq),
        .retrain_request(retrain_request)
    );
endmodule
